# -*- coding: utf-8 -*-
"""YOLO -1 Object Detction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wvY4iCOadrBY1OTEGNEe4PxIs1QORv3i
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics

import ultralytics
ultralytics.checks()

!yolo predict model = yolov8n.pt source = 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSdA_CdltD18dhBtvtAqU7GdxrXDHfUSZwaynUVwFZybA&s=10.jpeg'

!yolo predict model = yolo11n.pt source = 'https://c8.alamy.com/comp/R92782/handsome-young-man-working-on-laptop-while-enjoying-coffee-in-cafe-R92782.jpg'

!yolo predict model = yolo26n.pt source ='https://images.picxy.com/cache/2019/7/25/7cb6f63a656f23f38c4fff9a4cf219bc.jpg'

